services:
#    i_d_city_semantic_search.example:
#        class: iDCity\SemanticSearchBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]

    SemanticSearchBundle.getArticles:
        class: iDCity\SemanticSearchBundle\GetArticles


    SemanticSearchBundle.classifyArticles:
        class: iDCity\SemanticSearchBundle\ClassifyArticles



